import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";
import { connectMongoDB } from "@/lib/mongodb";
import { Provider } from "./provider";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await connectMongoDB()
  return (
    <html lang="en">
      <Provider>
        <body><Providers>{children}</Providers></body>
      </Provider>
    </html>
  );
}
